### ISSUE TITLE
Rate limit while ingesting

### ISSUE THREAD

**Issue by UnlimitedCookies** [Haste171/langchain-chatbot#78]
Hi there, we seem to be getting this error while ingesting a PDF document. We're on the Plus plan.
```
Ingesting 1 document(s)...
Params: chunk_size=1000, chunk_overlap=100, split_method=recursive
INFO:root:Ingesting 1 document(s)...
Params: chunk_size=1000, chunk_overlap=100, split_method=recursive
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.784918 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 1.514384 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO: 127.0.0.1:48524 - "POST /ingest HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Git/langchain-chatbot/endpoints/ingest.py", line 18, in ingest_documents
    handler.ingest_documents(documents)
  File "/home/user/Git/langchain-chatbot/handlers/base.py", line 156, in ingest_documents
    Pinecone.from_documents(
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 528, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/langchain_community/vectorstores/pinecone.py", line 435, in from_texts
    pinecone.add_texts(
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/langchain_community/vectorstores/pinecone.py", line 145, in add_texts
    embeddings = self._embed_documents(chunk_texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/langchain_community/vectorstores/pinecone.py", line 92, in _embed_documents
    return self._embedding.embed_documents(list(texts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 508, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 324, in _get_len_safe_embeddings
    response = self.client.create(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/resources/embeddings.py", line 113, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 965, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1013, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 965, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1013, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/langchain-chatbot-mUNeNTez-py3.11/lib/python3.11/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

**Comment by UnlimitedCookies** [comment]
Okay, a fault on our part, we weren't aware that the used developer api is different from regular chatgpt. Might help to clarify this in the `README.md`.
